name: Install Allure

description: Install Allure

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
        sudo tar -xzf allure-2.23.1.tgz -C /opt/
        sudo ln -sf /opt/allure-2.23.1/bin/allure /usr/bin/allure
        allure --version