name: Set Up Java

descriptions: Set up Temurin JDK

runs:
  using: composite
  steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - shell: bash
        run: java --version
        run: mvn --version
