name: API PetStore

on:
  push:
    branches:
      - develop

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Java -v 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - run: java --version
      - name: Check maven version
        run: mvn --version
      - name: Run Api test's
        run: mvn -pl api-ipr test