name: Manual Test Run (UI + API)

permissions:
  contents: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Test suite to run"
        required: true
        default: "all"
        type: choice
        options:
          - ui
          - api
          - all
      branch:
        description: "Branch to run tests from"
        equired: false
        default: develop

jobs:
  ui_tests:
    if: ${{ github.event.inputs.suite == 'ui' || github.event.inputs.suite == 'all' }}
    name: Run UI tests
    runs-on: ubuntu-latest

    env:
      TEST_EMAIL: ${{ secrets.TEST_MAIL }}
      PASSWORD_EMAIL: ${{ secrets.MAIL_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java 21
        uses: ./.github/actions/setup_java

      - name: Check Chrome
        run: |
          google-chrome --version || chromium-browser --version || true

      - name: Check Mail.ru
        run: curl -I https://mail.ru

      - name: Run UI Tests
        run: |
          mvn -pl ui-mail-ipr clean test \
            -Dheadless=true \
            -DtestEmail=$TEST_EMAIL \
            -DpasswordEmail=$PASSWORD_EMAIL
        continue-on-error: true

      - name: Upload ui allure results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: allure-results-ui
          path: ui-mail-ipr/target/allure-results
          retention-days: 3

  api-test:
    if: ${{ github.event.inputs.suite == 'api' || github.event.inputs.suite == 'all' }}
    runs-on: ubuntu-latest
    name: Run API tests

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Java -v 21
        uses: ./.github/actions/setup_java

      - name: Run Api test's
        run: mvn -pl api-ipr clean test
        continue-on-error: true

      - name: Upload api allure results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: allure-results-api
          path: api-ipr/target/allure-results
          retention-days: 3

  generate-allure:
    runs-on: ubuntu-latest
    needs: [api-test, ui_tests]
    name: Generate allure report
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download java
        uses: ./.github/actions/setup_java

      - name: Install Allure
        uses: ./.github/actions/install_allure

      - name: Download API results
        uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          name: allure-results-api
          path: allure-results/api

      - name: Download UI results
        uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          name: allure-results-ui
          path: allure-results/ui

      - name: Create empty dirs if missing
        run: |
          mkdir -p allure-results/api
          mkdir -p allure-results/ui

      - name: Merge results
        uses: ./.github/actions/merge_allure_res

      - name: Diagnose Allure
        run: |
          echo "TEST STATUS"
          echo $?
          echo "ALLURE DIR"
          ls -R ui-mail-ipr/target || true
          echo "SEARCH RESULTS"
          find . -name "*result.json" || true

      - name: Generate allure report
        run: allure generate -c allure-results --clean -o _site

      - name: Result generate
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: _site
          path: _site
          retention-days: 3

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: generate-allure
    name: Publish allure report

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      #      - name: Publish allure
      #        uses: peaceiris/actions-gh-pages@v4
      #        with:
      #          github_token: ${{ secrets.GITHUB_TOKEN }}
      #          publish_branch: gh-pages
      #          publish_dir: ./_site

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy GitHun Page
        id: deploy
        uses: actions/deploy-pages@v4